### ISSUE TITLE
Uncaught exception with hhvm-nightly

### ISSUE THREAD

**Issue by cjthomp** [PocketRent/hhvm-pgsql#42] opened 2014-12-05 16:23 UTC
Extensions (just the one) are in `/etc/hhvm/extensions` and `/etc/hhvm/php.ini` is updated properly.

> Uncaught exception: Could not open extension /etc/hhvm/extensions/pgsql.so: /etc/hhvm/extensions/pgsql.so: undefined symbol: _ZThn16_N4HPHP13PDOConnection5sweepEv\n

Downgrading to 3.4.0 works perfectly, though. I get the whole 'nightly is unstable' thing, so feel free to close this if necessary, but figured I'd do my due diligence and report it :)

**Comment by cjthomp** [comment] 2015-01-24 01:54
Update: now that hhvm stable is 3.5, `make` crashes every time. `no such file 'hphp/runtime/version.h'`

**Comment by jrobeson** [comment] 2015-02-06 07:56
@cjthomp : that issue was caused by hhvm itself. it should be fixed in updated packages.

**Comment by bountin** [comment] 2015-02-07 12:32
Here's hhvm's ticket for the version.h issue: https://github.com/facebook/hhvm/issues/4639

Looks like we have to wait for the 3.5.1 release.

**Closed** 2015-02-21 07:54 UTC
Labels: response needed
